### ISSUE TITLE
Request: F-Droid & GitHub releases

### ISSUE THREAD

**Issue by Sami32** [krakenfx/wallet#10]
It should be great to have direct Kraken wallet releases from GitHub APK & F-Droid IMHO.

**Comment by Hexcrypt** [comment]
Hi @Sami32! Agreed! We plan on publishing future releases with built APKs right here on GitHub. Look forward to it in the near future :raised_hands:

**Comment by Hexcrypt** [comment]
Our latest release includes a pre-built APK.
https://github.com/krakenfx/wallet/releases/tag/1.3.0

In the future we're looking to sign these in the release.
