### ISSUE TITLE
Missing files for external contributors

### ISSUE THREAD

**Issue by pedrosimao** [krakenfx/wallet#13]
Hello Krakenites,

I was interested in contributing to your open-source project and decided to try to deploy it locally.
Unhappily there seems to be some missing files. Some that I already found:

-  on `/src/App.tsx` I can't import this line `import { runMigrations } from './utils/migrations';`
- on `/src/hooks/useDebugInfo.ts` this statement this require won't work: ` const gitInfo = require('/git-info.json');`

After commenting those lines I still struggle with the following error:

`error: node_modules/react-native-reanimated/src/reanimated2/core.ts: .../kraken-wallet/node_modules/react-native-reanimated/src/reanimated2/core.ts: Cannot find module '@babel/plugin-proposal-optional-chaining'`

I have tried with and without Expo Go, just to get the same result. So, I guess I am out of luck.
I would be happy to assist you in making it easy for contributors to get onboarded on this project.

Cheers,
Pedro

**Comment by pedrosimao** [comment]
Are you using a specific version of node / yarn / expo?

**Comment by Hexcrypt** [comment]
Hi @pedrosimao, thank you for your interest in the project, and in contributing! The team is actively working internally to get the necessary files published to the GitHub repo that are required to build it here. Expect that in the near future we will have further updates on this, with instructions on building and contributing.

**Comment by Hexcrypt** [comment]
I'll leave this issue open and will update when the necessary support is added.

**Comment by dukejones** [comment]
Watching this - would love to get this building & maybe help improve it!

**Comment by NicolasMassart** [comment]
> After commenting those lines I still struggle with the following error:
>
> error: node_modules/react-native-reanimated/src/reanimated2/core.ts: .../kraken-wallet/node_modules/react-native-reanimated/src/reanimated2/core.ts: Cannot find module '@babel/plugin-proposal-optional-chaining'

@pedrosimao I added the required dependencies:
```bash
yarn add @babel/plugin-proposal-optional-chaining  @babel/plugin-proposal-nullish-coalescing-operator
```
Then run `yarn install` and `yarn android`.
![Screenshot_1717077893](https://github.com/krakenfx/wallet/assets/4677568/7774f601-0164-4c01-b064-b9ee6312bd1d)
But then when I try create the wallet, of course it crashes. Not always at the same moment, but it eventually crashes. So I believe that if Kraken team provides a proper repo with up to date debug files (I understand we don't have the keystores for release of course, but just provide the debug one which is not a secret) and then we only have to generate our own Firebase config file, then it will be a really simple and fast contributor experience.

**Comment by pedrosimao** [comment]
@NicolasMassart nice! Thanks for the tip. I will try on my side!
I faced some similar problems when trying to contribute to `metamask-mobile` repo some time ago. It's open source but there is no guide on how to get started with the project. To have the project running properly we would need external dependencies not available in the git repo itself. I am not sure it is still the case.
I guess making this kind of projects really open source is not that easy.

**Comment by Hexcrypt** [comment]
We have added some documentation on how to build and run the project locally, check out the [readme](https://github.com/krakenfx/wallet?tab=readme-ov-file#build-instructions) for details. :tada: 
We will be continuing to improve external contributor experience more as time goes on.

**Comment by shaung86** [comment]
Closing this as addressed. We will be further improving our documentation beyond basic contribution guidelines.
