### ISSUE TITLE
Turn off settings  code and News channel

### ISSUE THREAD

**Issue by umerbutt007** [krakenfx/wallet#16]
Close all coding formulas files

**Comment by Hexcrypt** [comment]
Really not sure what you mean, can you please give a more thorough description?

**Comment by Hexcrypt** [comment]
If you're experiencing an issue please let us know with a thorough report including screenshots and details.
If you're submitting a feature request please ensure there is a thorough description and reasoning for it.

Until then I'll close this issue, thank you for your interest in Kraken Wallet!
