### ISSUE TITLE
Received funds are marked as "Send" and incorrectly show the same address for sending and receiving

### ISSUE THREAD

**Issue by sethforprivacy** [krakenfx/wallet#4]
When testing out the Bitcoin portion of the wallet, I noticed that received funds are incorrectly marked as sends, and show the recipients address as the sending address. That also means that the amount of the transaction is displayed incorrectly. The pictured received transaction was from an external wallet to Kraken Wallet.

![image](https://github.com/krakenfx/wallet/assets/40500387/7e395903-061c-46b8-ac37-d9a4e86b1979)

**Comment by erickuhn19** [comment]
New build is shipping today with a fix
