### ISSUE TITLE
[Feature Request] Add Support for Ethereum Classic, Chain 61

### ISSUE THREAD

**Issue by chris-mercer** [krakenfx/wallet#9]
Hello, will you add support for Ethereum Classic (Chain 61) and its testnet Mordor (chain 63)? We would like to feature the Kraken wallet in the DeFi applications we are building at EthereumClassic.com Thanks in advance!

**Comment by shaung-kraken** [comment]
Thank you for the suggestion. We are actively reviewing chains that the Wallet will support and will be adding additional chains in the near future.
